### PR TITLE
#303 Promote and validation run not null.

### PR DESCRIPTION
**Pull request by flesire**

### CODE REVIEW

**Comment by dcoraboeuf** [comment]
Available in 2.13.10

**Comment by flesire** [comment]
I think that a new version of the jenkins plugin is required too.

**Comment by dcoraboeuf** [comment]
Can you create a PR? I do not have access to the code right now (holidays, mobile only) but I can merge and release easily

**Comment by dcoraboeuf** [comment]
You just have to update the Ontrack Dsl version in the pom file of the plugin - 2.13.10 in this case I assume

**Pull request merged**
